#!/usr/bin/env ruby

TEMPLATE = <<EOB
tmux has-session -t TMUX_NAME

if [ $? != 0 ]
then
  tmux new-session -s TMUX_NAME -n editor -d

  tmux send-keys -t TMUX_NAME 'cd DEV_DIR' C-m
  tmux send-keys -t TMUX_NAME 'vim .' C-m

  tmux split-window -v -p 25 -t TMUX_NAME

  tmux send-keys -t TMUX_NAME:1.2 'cd DEV_DIR' C-m

  # Servers
  tmux new-window -n servers -t TMUX_NAME
  tmux split-window -v -t TMUX_NAME:2

  tmux send-keys -t TMUX_NAME:2.1 'cd DEV_DIR' C-m
  tmux send-keys -t TMUX_NAME:2.1 'foreman start' C-m
  tmux send-keys -t TMUX_NAME:2.2 'cd DEV_DIR' C-m
  
  tmux select-pane -t TMUX_NAME:1.1
fi

tmux attach -t TMUX_NAME
EOB

if ARGV.length == 0
  $stderr.puts "Usage: #{File.basename(__FILE__)} path_to_dev_dir > name_of_tmux_script"
  abort
end

dev_dir = File.expand_path(ARGV[0] || '.')
dev_name = File.basename(dev_dir)
tmux_name = ARGV[1] || dev_name.downcase

$stdout.puts(TEMPLATE.gsub(/TMUX_NAME/, tmux_name).gsub(/DEV_DIR/, dev_dir))
